#!/bin/sh
while read file
do
	# c-x and 
        case "$1" in
        "C-x")
                trash-put "$file" ;;
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
