#!/bin/sh
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.
# montuje z root i 777 - ale chyba tak jest na fat
# nie działa notify-send przy sudo
# nie montuje Androida


# getmount() { \
# 	[ -z "$chosen" ] && exit 1
# 	mp="$(find $1 | dmenu -i -p "Type in mount point.")"
# 	[ "$mp" = "" ] && exit 1
# 	if [ ! -d "$mp" ]; then
# 		# create if doesn't exist
# 		mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
# 		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" ||  mkdir -p "$mp")
# 	fi
# 	}

# mountusb() { \
# 	chosen="$(echo "$usbdrives" | rofi -i -dmenu -p "Mount which drive?" | awk '{print $1}')"
# 	mountpoints="/media/usb|/media/usb2"
# 	mountpoint="$(echo "$mountpoints" | rofi -i -sep '|' -dmenu -p "Mount which drive?" | awk '{print $1}')"
# 	mount "$chosen" "$mountpoint" && notify-send "💻 USB mounting" "$chosen mounted. to $mountpoint" && exit 0
# 	}
mountusb() { \
	chosen="$(echo "$usbdrives" | rofi -i -dmenu -p "Mount which drive?" | awk '{print $1}')"
	mount "$chosen" && notify-send "💻 USB mounting" "$chosen mounted." && exit 0
	mountpoints="/media/usb|/media/usb2"
	mp="$(echo "$mountpoints" | rofi -i -sep '|' -dmenu -p "Mount which drive?" | awk '{print $1}')"
	# mount "$chosen" "$mp"
	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$2=="part"&&$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not \( -path *%s -prune \) \ \n",$3}')
	partitiontype="$(lsblk -no "fstype" "$chosen")"
	case "$partitiontype" in
		"vfat")  mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*)  mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')";  chown "$user":"$ug" 741 "$mp";;
		# *)  mount "$chosen" "$mp";  chown miro:miro 741 "$mp";;
	esac
	notify-send "💻 USB mounting" "$chosen mounted to $mp."
	}

mountandroid() { \
	chosen=$(echo "$anddrives" | dmenu -i -p "Which Android device?" | cut -d : -f 1)
	simple-mtpfs --device "$chosen" /media/android
	notify-send "🤖 Android Mounting" "Android device mounted."
	}

asktype() { \
	case $(printf "USB\\nAndroid" | dmenu -i -p "Mount a USB drive or Android device?") in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
	}

anddrives=$(simple-mtpfs -l 2>/dev/null)
usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""&&!/111|74/{printf "%s (%s)\n",$1,$3}')"
# usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
mountusb
# if [ -z "$usbdrives" ]; then
# 	echo "USB drive(s) detected."
# 	echo $usbdrives
# 	mountusb
# else
# 	echo "no usb devices"

# fi

# if [ -z "$usbdrives" ]; then
# 	[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && exit
# 	echo "Android device(s) detected."
# 	mountandroid
# else
# 	if [ -z "$anddrives" ]; then
# 		echo "USB drive(s) detected."
# 	       	mountusb
# 	else
# 		echo "Mountable USB drive(s) and Android device(s) detected."
# 		asktype
# 	fi
# fi
