#!/bin/sh

if [[ $1 == "horizontal" ]] 
then
xrandr --output DVI-I-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-I-1 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DVI-D-0 --primary --mode 1920x1200 --pos 0x360 --rotate normal &
else
# pivot
xrandr --output DVI-I-0 --mode 1920x1080 --pos 1920x0 --rotate left --output DVI-I-1 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DVI-D-0 --primary --mode 1920x1200 --pos 0x360 --rotate normal &
fi
