# Configuration documentation is available at https://dystroy.org/broot
# internal - overrite shortcut

#####################
icon_theme = "vscode"
# modal = true

# files aren't open in $EDITOR 
[[verbs]]
key = "ctrl-o"
invocation = "edit"
shortcut = "e"
execution = "/usr/bin/nvim {file}"
leave_broot = false
# execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-o"
shortcut = "f"
invocation = "open_stay_filter"
internal = ":open_stay_filter"

[[verbs]]
key = "ctrl-s"
invocation = "toggle_stage"
internal= ":toggle_stage"
[[verbs]]
key = "ctrl-z"
invocation = "stage_all"
internal = ":stage_all_files"

## VIMLIKE
[[verbs]]
key = "ctrl-k"
invocation = "line_up"
internal = ":line_up"
[[verbs]]
key = "ctrl-j"
invocation = "line_down"
internal = ":line_down"
[[verbs]]
key = "ctrl-l"
invocation = "open_stay"
internal = ":open_stay"
[[verbs]]
key = "ctrl-h"
invocation = "parent"
internal = ":parent"
[[verbs]]
key = "ctrl-u"
invocation = "page_up"
internal = ":page_up"
[[verbs]]
key = "ctrl-d"
invocation = "page_down"
internal = ":page_down"
[[verbs]]
key = "ctrl-g"
invocation = "bottom"
internal = ":select_last"

##### Panels
[[verbs]]
key = "ctrl-v"
invocation = "panel_new"
internal = ":start_end_panel"
[[verbs]]
key = "ctrl-w"
invocation = "toggle_preview"
internal = ":toggle_preview"
#can't change to c-q
[[verbs]]
key = "ctrl-c"
invocation = "close_panel_cancel"
internal = ":close_panel_cancel"
[[verbs]]
key = "ctrl-p"
invocation = "panel_left"
internal = ":panel_left"
[[verbs]]
key = "ctrl-n"
invocation = "panel_right"
internal = ":panel_right"
[[verbs]]
key = "ctrl-x"
invocation = "clear_stage"
internal = ":clear_stage"

# toggles
[[verbs]]
key = "ctrl-t"
invocation = "toggle_dates"
internal = ":toggle_dates"
[[verbs]]
key = "ctrl-a"
invocation = "toggle_hidden"
internal = ":toggle_hidden"
# doesn't work
[[verbs]]
key = "ctrl-i"
invocation = "toggle_git_ignore"
internal = ":toggle_git_ignore"
[[verbs]]
key = "ctrl-f"
invocation = "toggle_files"
internal = ":toggle_files"
[[verbs]]
key = "F9"
invocation="toggle_perm"
internal = ":toggle_perm"
##### SORT
[[verbs]]
key = "F10"
invocation="sort_by_size"
internal = ":sort_by_size"
[[verbs]]
key = "F11"
invocation="sort_by_date"
internal = ":sort_by_date"
[[verbs]]
key = "F12"
invocation="sort_by_type"
internal = ":sort_by_type"

##### EXECUTION
[[verbs]]
invocation = "remove"
key = "ctrl-r"
leave_broot = false
execution = "trash-put {file}"
# or {directory} it not match dir or file it will delete parrent!
# execution = "rm -rf {file}"
[[verbs]]
key = "F1"
invocation = "refresh"
internal = ":refresh"
[[verbs]]
key = "F5"
invocation = "copy_to_panel"
execution = "cp -r {file} {other-panel-directory}"
leave_broot = false
# internal = ":cpp" can't be overrited 
[[verbs]]
key = "F6"
invocation = "move_to_panel"
execution = "mv {file} {other-panel-directory}"
leave_broot = false
# internal = ":move_to_panel" can't be overrited 
[[verbs]]
key = "F7"
invocation = "mkdir {new_dir}"
execution = "/bin/mkdir -p {directory}/{new_dir}"
leave_broot = false
# execution = "mkdir -p {subpath:path-from-directory}"
[[verbs]]
key = "F8"
invocation = "touch {new_file}"
execution = "touch {directory}/{new_file}"
leave_broot = false

# BOOKMARKS
[[verbs]]
invocation = "home"
key = "alt-h"
internal = ":focus ~/"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
# execution = "$PAGER {file}"
#####################
# Skin

# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values
# Note that some of those colors might not correcly
# render on terminals with low capabilities
#
# [skin]
# default = "gray(20) gray(1)"
# tree = "rgb(89, 73, 101) none"
# file = "gray(21) none"
# directory = "rgb(255, 152, 0) none bold"
# exe = "rgb(17, 164, 181) none"
# link = "Magenta none"
# pruning = "rgb(89, 73, 101) none Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "gray(12) none"
# group = "gray(12) none"
# selected_line = "none gray(3)"
# char_match = "yellow none"
# file_error = "Red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "White none"
# status_error = "Red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3)"
# status_italic = "rgb(255, 152, 0) None"
# status_bold = "rgb(255, 152, 0) None bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "Magenta rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds



# [[verbs]]
# invocation = "open file"
# key = "ctrl-o"
# execution = "xdg-open {file}"
# apply_to = "file"

