
# This configuration file lets you define new commands
# or change the shortcut or triggering keys of built-in verbs.
# You can change the colors of broot too.
#
# Configuration documentation is available at https://dystroy.org/broot
#

#####################
# user defined verbs:

# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
# export EDITOR=/usr/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
# execution = "/usr/bin/nvim {file}"

[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "/usr/bin/nvim {file}"
leave_broot = false
# execution = "$EDITOR {file}"

[[verbs]]
shortcut = "f"
invocation = "open file"
key = "ctrl-o"
internal = ":open_stay_filter"

[[verbs]]
invocation = "home"
key = "ctrl-b"
internal = ":focus ~"

## VIMLIKE
[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
name = "line_down"
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-l"
execution = ":open_stay"

[[verbs]]
key = "ctrl-h"
execution = ":parent"

[[verbs]]
invocation = "top"
key = "ctrl-u"
execution = ":select_first"

[[verbs]]
invocation = "bottom"
key = "ctrl-d"
execution = ":select_last"

##### Panels
[[verbs]]
invocation = "panel_new"
key = "ctrl-v"
internal = ":start_end_panel"
[[verbs]]
invocation = "panel_close"
key = "ctrl-c"
internal = ":close_panel_cancel"
[[verbs]]
invocation = "panel_left"
key = "ctrl-p"
internal = ":panel_left"
[[verbs]]
invocation = "panel_right"
key = "ctrl-n"
internal = ":panel_right"


# toggles
[[verbs]]
name = "preview"
key = "ctrl-w"
invocation = "preview"
execution = ":toggle_preview"

[[verbs]]
key = "ctrl-t"
execution = ":toggle_dates"

[[verbs]]
key = "ctrl-a"
execution = ":toggle_hidden"

[[verbs]]
key = "ctrl-f"
execution = ":toggle_files"

[[verbs]]
key = "ctrl-x"
execution = ":toggle_perm"

[[verbs]]
key = "ctrl-s"
execution = ":toggle_sizes"

##### EXECUTION
[[verbs]]
invocation = "remove"
key = "ctrl-r"
leave_broot = false
execution = "trash-put {file}"
# or {directory} it not match dir or file it will delete parrent!
# execution = "rm -rf {file}"

[[verbs]]
invocation = "copy to panel"
key = "F5"
execution = "cp -r {file} {other-panel-directory}"
leave_broot = false

[[verbs]]
invocation = "move to panel"
key = "F6"
execution = "mv {file} {other-panel-directory}"
leave_broot = false

[[verbs]]
invocation = "move to panel"
key = "F8"
execution = "touch {directory}/{new_file}"
leave_broot = false

[[verbs]]
key = "F7"
invocation = "mkdir"
execution = "/bin/mkdir -p {directory}/{new_dir}"
leave_broot = false
# execution = "mkdir -p {subpath:path-from-directory}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
# execution = "$PAGER {file}"
#####################
# Skin

# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values
# Note that some of those colors might not correcly
# render on terminals with low capabilities
#
# [skin]
# default = "gray(20) gray(1)"
# tree = "rgb(89, 73, 101) none"
# file = "gray(21) none"
# directory = "rgb(255, 152, 0) none bold"
# exe = "rgb(17, 164, 181) none"
# link = "Magenta none"
# pruning = "rgb(89, 73, 101) none Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "gray(12) none"
# group = "gray(12) none"
# selected_line = "none gray(3)"
# char_match = "yellow none"
# file_error = "Red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "White none"
# status_error = "Red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3)"
# status_italic = "rgb(255, 152, 0) None"
# status_bold = "rgb(255, 152, 0) None bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "Magenta rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds



# [[verbs]]
# invocation = "open file"
# key = "ctrl-o"
# execution = "xdg-open {file}"
# apply_to = "file"

