#!/bin/sh

## Automount removable media
devmon &
# udiskie &
numlockx &
#screen saver
xset dpms 6000 6000 6000 s 6000 &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
sleep 500 && megasync &
clipster -d &
redshift -l 51.2:22.6 &
trackball.sh &
nm-applet &
nvidia-fan.sh -c ~/.config/nfancurve/config &
today-gcal.sh &

abduco -n tor rtorrent &!
#clipit &
#easystroke &
