" Name:         Penumbra
" Description:  Template for Penumbra dark colorscheme
" Author:       Michael Bulat
" Maintainer:   Michael Bulat
" License:      MIT
" Last Updated: Tue Aug 30 08:50:19 2022

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'penumbra'

let s:t_Co = exists('&t_Co') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#303338', '#ca736c', '#47a477', '#8d9741', '#5794d0', '#bc73a4', '#00a2af', '#8f8f8f', '#3e4044', '#ba823a', '#50b584', '#9ca748', '#61a3e6', '#9481cc', '#00b3c2', '#bebebe']
endif
hi Normal guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi Terminal guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi ColorColumn guifg=fg guibg=#ca736c gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#3e4044 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#3e4044 gui=NONE cterm=NONE
hi CursorLineNr guifg=NONE guibg=#3e4044 gui=bold cterm=bold
hi DiffAdd guifg=#47a477 guibg=#3e4044 guisp=#47a477 gui=NONE cterm=NONE
hi DiffChange guifg=#8d9741 guibg=#3e4044 guisp=#8d9741 gui=NONE cterm=NONE
hi DiffDelete guifg=#ca736c guibg=#3e4044 gui=bold cterm=bold
hi DiffText guifg=#5794d0 guibg=#3e4044 guisp=#5794d0 gui=NONE cterm=NONE
hi Directory guifg=#5794d0 guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi ErrorMsg guifg=#ca736c guibg=#303338 gui=reverse cterm=reverse
hi FoldColumn guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi Folded guifg=#8f8f8f guibg=#3e4044 gui=italic cterm=italic
hi IncSearch guifg=#47a477 guibg=#303338 gui=standout cterm=reverse
hi LineNr guifg=#636363 guibg=#3e4044 gui=NONE cterm=NONE
hi MatchParen guifg=#fff7ed guibg=#303338 gui=NONE cterm=NONE
hi ModeMsg guifg=#5794d0 guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#5794d0 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#ba823a guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#8f8f8f guibg=#24272b gui=NONE cterm=NONE
hi PmenuSbar guifg=#8f8f8f guibg=#24272b gui=NONE cterm=NONE
hi PmenuSel guifg=#8f8f8f guibg=#fff7ed gui=reverse cterm=reverse
hi PmenuThumb guifg=#8f8f8f guibg=#3e4044 gui=NONE cterm=NONE
hi Question guifg=#00a2af guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#8d9741 guibg=NONE gui=reverse cterm=reverse
hi SignColumn guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi SpecialKey guifg=#47a477 guibg=#3e4044 gui=NONE cterm=NONE
hi SpellBad guifg=#ca736c guibg=NONE guisp=#ca736c gui=reverse,undercurl cterm=reverse,underline
hi SpellCap guifg=#9481cc guibg=NONE guisp=#ba823a gui=reverse,undercurl cterm=reverse,underline
hi SpellLocal guifg=#8d9741 guibg=NONE guisp=#8d9741 gui=reverse,undercurl cterm=reverse,underline
hi SpellRare guifg=#00a2af guibg=NONE guisp=#00a2af gui=reverse,undercurl cterm=reverse,underline
hi StatusLine guifg=#8f8f8f guibg=#303338 gui=reverse cterm=reverse
hi StatusLineNC guifg=#8f8f8f guibg=#fff7ed gui=reverse cterm=reverse
hi TabLine guifg=#8f8f8f guibg=#303338 gui=reverse cterm=reverse
hi TabLineFill guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi TabLineSel guifg=#5794d0 guibg=#303338 gui=reverse cterm=reverse
hi Title guifg=#ba823a guibg=NONE gui=bold cterm=bold
hi VertSplit guifg=#8f8f8f guibg=#303338 gui=NONE cterm=NONE
hi Visual guifg=#8f8f8f guibg=#303338 gui=reverse cterm=reverse
hi VisualNOS guifg=NONE guibg=#24272b gui=reverse cterm=reverse
hi WarningMsg guifg=#ba823a guibg=#303338 gui=NONE cterm=NONE
hi WildMenu guifg=#fff7ed guibg=#303338 gui=reverse cterm=reverse
hi Comment guifg=#636363 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#00a2af guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#ca736c guibg=#303338 gui=reverse cterm=reverse
hi Identifier guifg=#5794d0 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PreProc guifg=#ca736c guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#47a477 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#8d9741 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#bc73a4 guibg=NONE gui=bold cterm=bold
hi Type guifg=#ba823a guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#9481cc guibg=NONE gui=NONE cterm=NONE
hi CursorIM guifg=#303338 guibg=fg gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#303338 gui=NONE cterm=NONE
hi ToolbarButton guifg=#8f8f8f guibg=#303338 gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  hi Normal ctermfg=246 ctermbg=236 cterm=NONE
  hi Terminal ctermfg=246 ctermbg=236 cterm=NONE
  hi ColorColumn ctermfg=fg ctermbg=167 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=246 ctermbg=236 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=238 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=238 cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=238 cterm=bold
  hi DiffAdd ctermfg=72 ctermbg=238 cterm=NONE
  hi DiffChange ctermfg=100 ctermbg=238 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=238 cterm=bold
  hi DiffText ctermfg=67 ctermbg=238 cterm=NONE
  hi Directory ctermfg=67 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=236 cterm=reverse
  hi FoldColumn ctermfg=246 ctermbg=236 cterm=NONE
  hi Folded ctermfg=246 ctermbg=238 cterm=italic
  hi IncSearch ctermfg=72 ctermbg=236 cterm=reverse
  hi LineNr ctermfg=241 ctermbg=238 cterm=NONE
  hi MatchParen ctermfg=255 ctermbg=236 cterm=NONE
  hi ModeMsg ctermfg=67 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=67 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=137 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=246 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=246 ctermbg=235 cterm=NONE
  hi PmenuSel ctermfg=246 ctermbg=255 cterm=reverse
  hi PmenuThumb ctermfg=246 ctermbg=238 cterm=NONE
  hi Question ctermfg=37 ctermbg=NONE cterm=NONE
  hi Search ctermfg=100 ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=236 cterm=NONE
  hi SpecialKey ctermfg=72 ctermbg=238 cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=reverse,underline
  hi SpellCap ctermfg=104 ctermbg=NONE cterm=reverse,underline
  hi SpellLocal ctermfg=100 ctermbg=NONE cterm=reverse,underline
  hi SpellRare ctermfg=37 ctermbg=NONE cterm=reverse,underline
  hi StatusLine ctermfg=246 ctermbg=236 cterm=reverse
  hi StatusLineNC ctermfg=246 ctermbg=255 cterm=reverse
  hi TabLine ctermfg=246 ctermbg=236 cterm=reverse
  hi TabLineFill ctermfg=246 ctermbg=236 cterm=NONE
  hi TabLineSel ctermfg=67 ctermbg=236 cterm=reverse
  hi Title ctermfg=137 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=246 ctermbg=236 cterm=NONE
  hi Visual ctermfg=246 ctermbg=236 cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=235 cterm=reverse
  hi WarningMsg ctermfg=137 ctermbg=236 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=236 cterm=reverse
  hi Comment ctermfg=241 ctermbg=NONE cterm=italic
  hi Constant ctermfg=37 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=236 cterm=reverse
  hi Identifier ctermfg=67 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=72 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=100 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=169 ctermbg=NONE cterm=bold
  hi Type ctermfg=137 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=104 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=236 ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=246 ctermbg=236 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  hi Normal ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi Terminal ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi ColorColumn ctermfg=fg ctermbg=DarkRed cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=DarkGray cterm=bold
  hi DiffAdd ctermfg=DarkGreen ctermbg=DarkGray cterm=NONE
  hi DiffChange ctermfg=DarkYellow ctermbg=DarkGray cterm=NONE
  hi DiffDelete ctermfg=DarkRed ctermbg=DarkGray cterm=bold
  hi DiffText ctermfg=DarkBlue ctermbg=DarkGray cterm=NONE
  hi Directory ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=DarkGray cterm=reverse
  hi FoldColumn ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi Folded ctermfg=Gray ctermbg=DarkGray cterm=italic
  hi IncSearch ctermfg=DarkGreen ctermbg=DarkGray cterm=reverse
  hi LineNr ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi MatchParen ctermfg=White ctermbg=DarkGray cterm=NONE
  hi ModeMsg ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Gray ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=Gray ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Gray ctermbg=White cterm=reverse
  hi PmenuThumb ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi Question ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi SpecialKey ctermfg=DarkGreen ctermbg=DarkGray cterm=NONE
  hi SpellBad ctermfg=DarkRed ctermbg=NONE cterm=reverse,underline
  hi SpellCap ctermfg=DarkMagenta ctermbg=NONE cterm=reverse,underline
  hi SpellLocal ctermfg=DarkYellow ctermbg=NONE cterm=reverse,underline
  hi SpellRare ctermfg=DarkCyan ctermbg=NONE cterm=reverse,underline
  hi StatusLine ctermfg=Gray ctermbg=DarkGray cterm=reverse
  hi StatusLineNC ctermfg=Gray ctermbg=White cterm=reverse
  hi TabLine ctermfg=Gray ctermbg=DarkGray cterm=reverse
  hi TabLineFill ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi TabLineSel ctermfg=DarkBlue ctermbg=DarkGray cterm=reverse
  hi Title ctermfg=Brown ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Gray ctermbg=DarkGray cterm=NONE
  hi Visual ctermfg=Gray ctermbg=DarkGray cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=Black cterm=reverse
  hi WarningMsg ctermfg=Brown ctermbg=DarkGray cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkGray cterm=reverse
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=DarkGray cterm=reverse
  hi Identifier ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=DarkGray ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi ToolbarButton ctermfg=Gray ctermbg=DarkGray cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: sunplus       rgb(255, 253, 251)        231         White
" Color: sun           rgb(255, 247, 237)        255         White
" Color: sunminus      rgb(242, 230, 212)        254         White
" Color: skyplus       rgb(190, 190, 190)        250         LightGray
" Color: sky           rgb(143, 143, 143)        246         Gray
" Color: skyminus      rgb( 99,  99,  99)        241         Gray
" Color: shadeplus     rgb( 62,  64,  68)        238         DarkGray
" Color: shade         rgb( 48,  51,  56)        236         DarkGray
" Color: shademinus    rgb( 36,  39,  43)        235         Black
" Color: red           rgb(202, 115, 108)        167         DarkRed
" Color: orange        rgb(186, 130,  58)        137         Brown
" Color: yellow        rgb(141, 151,  65)        100         DarkYellow
" Color: green         rgb( 71, 164, 119)        72          DarkGreen
" Color: cyan          rgb(  0, 162, 175)        37          DarkCyan
" Color: blue          rgb( 87, 148, 208)        67          DarkBlue
" Color: purple        rgb(148, 129, 204)        104         DarkMagenta
" Color: magenta       rgb(188, 115, 164)        169         LightMagenta
" Color: redplus       rgb(223, 127, 120)        174         Red
" Color: orangeplus    rgb(206, 144,  66)        172         Brown
" Color: yellowplus    rgb(156, 167,  72)        143         LightYellow
" Color: greenplus     rgb( 80, 181, 132)        72          LightGreen
" Color: cyanplus      rgb(  0, 179, 194)        37          LightCyan
" Color: blueplus      rgb( 97, 163, 230)        75          LightBlue
" Color: purpleplus    rgb(164, 143, 225)        140         LightMagenta
" Color: magentaplus   rgb(208, 128, 182)        175         LightMagenta
" Color: redplusplus     rgb(245, 140, 129)        210         Red
" Color: orangeplusplus  rgb(224, 159,  71)        215         Brown
" Color: yellowplusplus  rgb(169, 184,  82)        143         LightYellow
" Color: greenplusplus   rgb( 84, 199, 148)        79          LightGreen
" Color: cyanplusplus    rgb(  0, 196, 215)        80          LightCyan
" Color: blueplusplus    rgb(110, 178, 253)        75          LightBlue
" Color: purpleplusplus  rgb(182, 156, 246)        147         LightMagenta
" Color: magentaplusplus rgb(229, 140, 197)        175         LightMagenta
" Term colors: shade red green yellow blue magenta cyan sky
" Term colors: shadeplus orange greenplus yellowplus
" Term colors: blueplus purple cyanplus skyplus
" vim: et ts=2 sw=2
