#!/usr/bin/env bash
[[ $1 == 'rofi' ]] && launcher="rofi -monitor -4 -dmenu" || launcher="fzf"

manual=$(apropos -s ${SECTION:-''} ${@:-.} | \
    grep -v -E '^.+ \(0\)' | \
    awk '{print $2 "    " $1}' | \
	sort | \
    $launcher  | \
    sed -E 's/^\((.+)\)/\1/')

[ -z "$manual" ] && exit 0

manExe="man $manual"

if [[ $1 == 'rofi' ]] 
then
	eval $(printf "$TERMINAL $TERM_RUN" "man" "man $manExe")
else
	$manExe
fi
